### ISSUE TITLE
trailing curly brace being stripped from slot value

### ISSUE THREAD

**Issue by Shotgun167** [snipsco/snips-nlu-ontology#139] opened 2019-04-30 20:58 UTC
I have some values in slots that are surrounded by curly braces and are meant to be returned as is.  Instead, the trailing brace is being stripped.  "${website}" becomes "${website".  I have training examples where the whole "${website}" is included.  Is there a way to change this behavior?

**Comment by adrienball** [comment] 2019-05-02 08:34
I'm closing this issue as it's a duplicate of https://github.com/snipsco/snips-nlu/issues/793

**Closed by adrienball** 2019-05-02 08:34 UTC
