### ISSUE TITLE
Parsing failure impossible to diagnose

### ISSUE THREAD

**Issue by Shotgun167** [snipsco/snips-nlu-ontology#138] opened 2019-04-30 20:55 UTC
If you have a syntax error in a yaml training file, Snips will tell you something like:

Missing ending ']' in annotated utterance"

Good luck finding which utterance is missing that bracket.  

I found that adding " + state.input" to the exception string in input.py/capture_slot and input.py/capture_tagged would print the utterance, so that the fix was quick.

**Comment by adrienball** [comment] 2019-05-02 08:34
I'm closing this as it's a duplicate of https://github.com/snipsco/snips-nlu/issues/794

**Closed by adrienball** 2019-05-02 08:34 UTC
